const neighborhoods = [
  "Abattoir",
  "Adrar",
  "Aghroud 1",
  "Aghroud 2",
  "Ait melloul",
  "Al Fiddiya",
  "Al Qods",
  "Al Wifaq",
  "Alma",
  "Amsernat",
  "Anouar Souss",
  "Anza",
  "Aourir",
  "Autres",
  "Bensergao",
  "Charaf",
  "Cité Suisse",
  "Dakhla",
  "Dcheira",
  "Drarga",
  "El Farah",
  "El Houda",
  "El Massira",
  "Erac - Bouargane",
  "Essalam",
  "Extension Dakhla",
  "Founty",
  "Haut Founty",
  "Hay Al Wafa",
  "Hay Hassani",
  "Hay Mohammadi",
  "Ihchach",
  "Iligh",
  "Imi Ouaddar",
  "Inzegan",
  "La source",
  "Laazib",
  "Les Amicales",
  "Lkhyam 1",
  "Lkhyam 2",
  "Madraba",
  "Nahda",
  "Najah",
  "Quartier industriel",
  "Riad Salam",
  "Sidi Youssef",
  "Taddart",
  "Taghazout",
  "Taghazout Bay",
  "Taguadirt",
  "Talborjte 1",
  "Tamraght",
  "Tassila",
  "Temsia",
  "Temsia",
  "Tikiouine",
  "Tilila",
  "Zone touristique",
];

module.exports = neighborhoods;
